### ISSUE TITLE
Feature Request: Response_format parameter (for JSON outputs)

### ISSUE THREAD

**Issue by Jonseed** [glibsonoran/Plush-for-ComfyUI#121] opened 2024-10-10 16:37 UTC
It would be cool if the advanced prompt enhancer could include the response_format parameter in order to enable JSON mode with LLMs. This could be just [simple JSON mode](https://platform.openai.com/docs/guides/structured-outputs/json-mode) {"type": "json_object"}, or [Structured Outputs](https://platform.openai.com/docs/guides/structured-outputs/structured-outputs) where a JSON schema can also be provided. This would enable more complex interactions with the LLM, and output data could be more easily parsed from a single LLM query. For example, you could ask the LLM for a prompt in natural language form (for T5 encoder), and in tag form (for CLIP encoder), and then parse that JSON output into the two separate outputs for the dual text encoder node.

**Comment by glibsonoran** [comment] 2024-10-10 17:24
I'm looking at your request, no promises implied yet, but I have a couple of questions:

*   Which services that APE supports would be able to interpret these response formats?  Just OpenAI (and even within OpenAI it seems only specific models)?

*   Regarding the more explicit Structured Outputs:  In the examples the templates are implemented as Python classes in code.  Do you have a specific set of formats you think apply to ComfyUI's use case?  If so would you be able to provide specific template examples of what you're looking for?

**Comment by Jonseed** [comment] 2024-10-10 18:14
Any service that supports the OpenAI Chat Completions API seems like it could work, but other services might have a different formatting.

Groq [explicitly says](https://console.groq.com/docs/openai) they do _not_ support the `response_format` parameter, unfortunately.

OpenAI [supports](https://platform.openai.com/docs/guides/structured-outputs/structured-outputs-vs-json-mode) JSON Mode with `gpt-3.5-turbo`, `gpt-4-*` and `gpt-4o-*` models, and Structured Outputs with `gpt-4o-mini`, `gpt-4o-2024-08-06`, and later models.

Anthropic supports JSON outputs through two methods: [simple prompting](https://docs.anthropic.com/en/docs/test-and-evaluate/strengthen-guardrails/increase-consistency) it to respond in JSON and providing the schema in the prompt, or through [tool use (function calling)](https://docs.anthropic.com/en/docs/build-with-claude/tool-use#json-mode), but the latter method might be too complex.

Ollama supports JSON outputs in two ways: in the [native Ollama API](https://github.com/ollama/ollama/blob/main/docs/api.md#request-json-mode) with the `format` parameter which accepts a `json` value, or if you use [Ollama's OpenAI Chat Completions compatibility](https://github.com/ollama/ollama/blob/main/docs/openai.md) at the /v1 endpoint, then it supports the standard parameter: `response_format: { type: "json_object" }`.

With the Structured Outputs you don't have to implement it with a Python class, but rather can [provide a manual JSON schema](https://platform.openai.com/docs/guides/structured-outputs/how-to-use) like this:
```
response_format={
        "type": "json_schema",
        "json_schema": {
            "t5": "t5 encoder prompt",
            "clip": "clip encoder prompt"
            },
        "strict": True
        }
```
You could provide this example schema which would probably be most useful to Comfy users using Flux models that have the two text encoders that want two very different prompting styles, or allow a custom schema as input (you would probably want to validate that it is JSON). I currently want to use GPT models in a Comfy workflow to help me caption images with titles and descriptions, so my custom JSON schema would be something like this:

```
{
     "title": "title of art",
     "description": "description of art"
}
```

**Comment by glibsonoran** [comment] 2024-10-10 20:07
OK, this is something I'd have to think about.  It's fairly convoluted as to how to present this data to each service and which will actually accept them.  Something that will likely also change over time.  

I'm just trying to keep the project manageable for me in terms of updates and support.  

Do you have an Anthropic account?  It sounds like you can get data back in the format you want by embedding your schema in the prompt and/or reinforcing it by providing examples in the examples_context input, per your feedback.  

Also there's the issue of reading the resulting json.  In the case of Flux, while any LLM can read a json, is this particular format something that Flux can read in raw JSON format and apply the different prompts as intended ?  Or will that require some massaging.   Also for your captioning use case, do you have a way to read the JSON and apply it in a way that fits the final presentation?

**Comment by Jonseed** [comment] 2024-10-10 22:08
I have found that simple prompting to get JSON output from LLMs is very unreliable. Small models in particular are worse at this than large models. Forcing the API to return valid JSON output as a specific requested format of response is the most reliable and consistent method to get valid JSON back every time. For these kinds of programmatic use cases of LLMs, and parsing responses for data, it's quite handy. It can also greatly reduce the number of requests sent to the LLM (lower costs), since you can ask for many things in a single query, and have them all sent back in a single JSON response.

Reading the resulting JSON isn't a problem with other custom Comfy nodes such as the [LF Custom Nodes](https://github.com/lucafoscili/comfyui-lf). They can receive JSON, display JSON, get values from particular keys of JSON, convert between strings and JSON, and other kinds of JSON manipulation. So your node wouldn't have to do any of that, just output the JSON.

**Comment by Jonseed** [comment] 2024-10-12 00:31
I think the simpler JSON Mode would be sufficient to begin with, and pretty straightforward to implement.

All of the latest OpenAI models support it, and it is turned on by simply passing the parameter `response_format: { type: "json_object" }` with the request. The user can pass the schema to OpenAI in their prompt.

The very same parameter could be used for Ollama if using their OpenAI Chat Completions compatibility endpoint at `/v1` (which I assume one can do with the "OpenAI compatible http POST (URL)" option). If using Ollama API natively, the parameter changes to `"format": "json"`.

That's it. That covers many use cases and guarantees JSON responses. You could just not enable or pass the parameter for Groq and Anthropic services.

**Comment by glibsonoran** [comment] 2024-10-12 03:19
Ok, I have a rough prototype working on my dev side build.  You have some specific prompt/system parameters you have to meet or chatGPT will kick your request out.  I had to specify 'JSON' in the prompt or system instruction and give it the keys I wanted to use.  I do think this will be somewhat of a niche feature. 
Anyway here's a screenshot of the outcome:

![ReponseFormat](https://github.com/user-attachments/assets/249e947e-cd92-4920-ae2d-739a94f75763)

**Comment by glibsonoran** [comment] 2024-10-12 04:33
OK, so when using anything more than just json_object and a description in the prompt or system messages to describe how the output should appear, you have to use the chat.completions.parse() method and query the completion.choices[0].message.parsed value in the object.  
This would really complicate my code as I have various completions requests and objects based on different AI services local and remote.  I think I may just have to leave it at json_object and the user will have detail the specifics in one of the prompts.

**Comment by glibsonoran** [comment] 2024-10-12 05:23
Here's an example of using the plain json_object response_format with a descriptive prompt.  I think it's reasonable:

![ResponseFormat_2](https://github.com/user-attachments/assets/648f5537-af1e-4955-9029-1143564c68c7)

**Comment by glibsonoran** [comment] 2024-10-12 05:44
Just FYI, 
The "v1" endpoint would be associated with using the OpenAI API object and the corresponding menu item for a local app like Ollama would be: `Local app (URL)`.  The http POST method communicates directly with the server and uses the "v1/chat/completions" endpoint.

**Comment by Jonseed** [comment] 2024-10-12 16:23
> Here's an example of using the plain json_object response_format with a descriptive prompt.  I think it's reasonable:

I think that's great! I think that covers most needs without getting too technical or complex. Now you can make a single request to OpenAI API, and get back multiple answers to parse and use throughout a workflow. Much faster and saves cost!

Does the Ollama API parameter `"format": "json"` also work?

Just had another thought. I wonder if it would make sense to allow "other" miscellaneous parameters to include with the request, to allow users to customize the request however they choose? You could take input JSON of any other parameters the user chooses, and send them along with the request. That way you don't have to hardcode implement every new feature or variation of parameters that each service adds in the future.

**Comment by Jonseed** [comment] 2024-10-12 16:30
> Just FYI, 
> The "v1" endpoint would be associated with using the OpenAI API object and the corresponding menu item for a local app like Ollama would be: `Local app (URL)`.  The http POST method communicates directly with the server and uses the "v1/chat/completions" endpoint.

So if you want to use [Ollama's OpenAI compatibility mode](https://ollama.com/blog/openai-compatibility), you could just set the Local app URL to `http://localhost:11434/v1/chat/completions` ?

**Comment by glibsonoran** [comment] 2024-10-12 18:05
Re: other misc parameters.  I thought about that last night and added a *Parameter_name* field the user can enter along with the *User_json*.  So I'm just going to leave it up to the user to determine how to introduce this parameter to their favorite LLM, they have the tools to send this to anything that: Doesn't require using a completions method other than *chat.completions.create()* and can accept some form of response format input. [see attached pic]

Using Ollama with `Local app (URL)` you will be using the OpenAI API object and your endpoint will be 'http://localhost:11434/v1', which should correspond with the *response_format* parameter name.  That Local app {URL} menu item actually corrects the url path so even if you were to put `v1/chat/completions` as your path it would correct it.

Web based requests talk directly to the server and typically need the full 'http://localhost:11434/v1/chat/completions' endpoint.  I don't validate and correct this path because there are too many possible variables in web addresses.

![ResponseFormat_3](https://github.com/user-attachments/assets/ac55b680-9daf-48e1-b619-d69efb9384a4)

**Comment by glibsonoran** [comment] 2024-10-12 18:18
I'm thinking I'd like to add a simple node that takes a 'JSON' (really it's a python dict in this case) and can parse out all the key value pairs and send the values to different outputs.  
So you'd have a node with a "JSON" labeled input and say five text fields to enter your key names (e.g. output_key_1, output_key_2) and five potential outputs numbered 1 - 5 to output string values.
You mentioned some other json node, does it handle this?  I do like to make it so users don't have to download a bunch of other nodes in order to make things work.

**Comment by glibsonoran** [comment] 2024-10-12 18:37
Regarding handling any parameter:  Yes, I could add a button to have the user indicate if the parameter value is a JSON, then just pass plain text if it was unchecked only validating the JSON if the item was checked.

**Comment by Jonseed** [comment] 2024-10-12 19:03
> You mentioned some other json node, does it handle this? I do like to make it so users don't have to download a bunch of other nodes in order to make things work.

Yes, [LF Custom Nodes](https://github.com/lucafoscili/comfyui-lf) has all kinds of JSON manipulation nodes, including a node that can parse JSON called [`GetValueFromJSON`](https://github.com/lucafoscili/comfyui-lf?tab=readme-ov-file#getvaluefromjson), but it only retrieves a single value from a specified key. "Extracts a specific value from a JSON object based on a provided key. This node supports extracting various types of values including JSON objects, strings, numbers, integers, floats, and booleans."
![GetValueFromJSON](https://github.com/user-attachments/assets/3dca9583-1884-450e-a6a5-a7a9ec013241)

You could expand on that node to allow multiple key-value pairs. The difficulty might be handling the various output types other than string, unless you could specify the type of output for each value in another field. By the way, that node seems to be missing the `list` type of output, which I've actually been wanting to use.

**Comment by Jonseed** [comment] 2024-10-12 19:10
> Doesn't require using a completions method other than _chat.completions.create()_ and can accept some form of response format input.

That's unfortunate that OpenAI requires a completely different method to handle and parse responses when using Structured Outputs. Makes it more difficult to implement that mode. But I think the simpler JSON mode will probably work for most use cases.

**Comment by glibsonoran** [comment] 2024-10-12 19:29
Hmm, I don't see where you specify the data type, so it must be determining that by examining the value.  Like if it starts with a "{" it's a json?  Guess I'd have to look at the code.  It's not like you can shield the user from having to know the data type because they still have to hook up the right output, so...  So maybe you avoid the issue where the user specifies int and sends you a bunch of letters, but you can hamper the user who wants their numeric value presented as a string.

Otherwise that way works too, you just have to put several nodes in-line to parse your different key/value pairs.

**Comment by Jonseed** [comment] 2024-10-12 19:35
Yeah, this is how they are detecting the data type of the value.

```
def on_exec(self, json: dict, key: str, index: int):
        if isinstance(json, list):
            length = len(json)
            json = json[index] if index < length else json[length - 1]

        value = json.get(key, None)

        json_output = None
        string_output = None
        number_output = None
        int_output = None
        float_output = None
        boolean_output = None

        if value is not None:
            if isinstance(value, dict):
                json_output = value
            else:
                json_output = {"value": value}
            
            string_output = str(value)
            
            if isinstance(value, str):
                try:
                    numeric_value = float(value)
                    number_output = numeric_value
                    float_output = numeric_value
                    int_output = round(numeric_value) if numeric_value.is_integer() else None
                    boolean_output = numeric_value > 0
                except ValueError:
                    pass
            elif isinstance(value, (int, float)):
                number_output = value
                float_output = float(value)
                int_output = round(value) if isinstance(value, float) else value
                boolean_output = value > 0
            elif isinstance(value, bool):
                boolean_output = value
            else:
                number_output = None
                int_output = None
                float_output = None

        return (json_output, string_output, number_output, int_output, float_output, boolean_output)
```
It looks like they have added an index value now to the node as well: "When the input is a list of JSON objects, it sets the index of the occurrence from which the value is extracted."

**Comment by glibsonoran** [comment] 2024-10-12 19:47
That's a pretty good method, so he provides the output in all available formats that are valid for the input value.  What is this typically handling output from?  I haven't been using Comfy for a while, are there lots of nodes with JSON output now?

**Comment by Jonseed** [comment] 2024-10-12 19:55
I don't know of many nodes that output JSON, but I think that will change soon. I think JSON is just a good data exchange format, and many people are using Comfy for other kinds of workflows than just image generation. JSON is a great way to shuttle data around their workflows. It's what I'm using, for example, to help me title and keyword my images. I still have to use an external python script to inject the EXIF metadata, but being able to dump the data from Comfy in JSON is great.

**Comment by glibsonoran** [comment] 2024-10-12 20:10
Regarding using chat.completions.parse() vs chat.completions.create()  for Structured outputs:  I wouldn't be surprised if they have code that parses your JSON and then constructs a prompt to describe it to the model when you use the parse method.  And actually that wouldn't be too bad except then you have to query a different key in the response object to get the return value: completion.choices[0].message.parsed.  Also you should handle yet another key from that object in the case the model refuses to handle your request because it would violate policy.  This is a 'refusal' key/value. 

Oy, that response object is already so hard to handle with all the different places that different services put their error information, and the slightly different structures they use.  If my node were only handling one or two AI services maybe I'd try it, but not with this many.

**Comment by Jonseed** [comment] 2024-10-12 20:39
The `Save Image with Extra Metadata` node in the popular [ComfyUI-Crystools](https://github.com/crystian/ComfyUI-Crystools) is an example of one that can input/output stringified "JSON". Oddly, it is not true JSON input/output, but a "METADATA_RAW" which I think is a string. So I can't link up the IO of that node to any of the LF Nodes JSON I/O.

![image-save (1)](https://github.com/user-attachments/assets/db59938d-7162-453b-8d4d-7c8791371d5e)

This node can inject metadata via JSON in the saved image, but unfortunately I don't think it currently does this correctly for keywords (so they can be easily imported in Lightroom), so I can't use it. I'm currently investigating to see if that node can be easily modified to inject keywords EXIF correctly.

**Comment by glibsonoran** [comment] 2024-10-12 20:59
Hmm, I have a node that extracts Exif & XMP from jpeg's (and maybe .raw's) and ComfyUI meta data from .png's: *Exif_Wrangler*.  
But it doesn't produce output in JSON format and it doesn't add meta data.  If you look at the code for *style_prompt.py* down near the end of the file there's a big dictionary named 'exif-keys' that's a list of all the exif and xmp data it gathers.

**Comment by Jonseed** [comment] 2024-10-12 21:59
Yes, I saw your EXIF Wrangler node, which could be helpful if I need to read EXIF data back into Comfy. For some reason it can't read some of my PNG files, which have both Auto1111 metadata and EXIF data I've injected with ExifTool. I get the error: `Unable to process image file,` and in troubleshooting it says `WARNING: Unable to process Image file: 'utf-8' codec can't decode byte 0x96 in position 816: invalid start byte.` ExifTool can read the file fine. 🤔

**Comment by glibsonoran** [comment] 2024-10-13 02:10
So I've got my prototypes up now with the JSON parsing node.  I think I have to change the name of that first field in additional parameters to Parameter Type, but otherwise this is the gist.
The JSON node you showed me is a much better general purpose node for parsing JSON's.  But my suite is very prompt oriented so this JSON parsing node is oriented toward string input and output, meaning you don't have to present a JSON object to it, it will take the string JSON and convert it, and the output is all strings ready to be sent to text/image encoders.

![Params_And_Parse](https://github.com/user-attachments/assets/6cc48587-d497-4a31-8a25-449b6ed6d105)

**Comment by glibsonoran** [comment] 2024-10-13 03:41
And here it handles a list of dictionaries:

![ParseOnly](https://github.com/user-attachments/assets/fd92c57b-111a-4d4b-a97e-2cf2c7a77988)

**Comment by glibsonoran** [comment] 2024-10-13 04:13
And here it handles a list of dictionaries with duplicate keys (it puts the values from the duplicate keys in a list):

![ParseOnlyDupes](https://github.com/user-attachments/assets/f97ddd0c-71ed-40af-9c3a-33b7390221e4)

**Comment by glibsonoran** [comment] 2024-10-13 04:56
Sorry one last one before I go to bed.  A nested JSON structure:

![ParseNested](https://github.com/user-attachments/assets/663f8f1d-378e-4dca-8c56-868f247abd68)

**Comment by Jonseed** [comment] 2024-10-13 05:25
This is looking great! Can't wait to try it out!

**Comment by EnragedAntelope** [comment] 2024-10-13 13:01
I have been following along with this and just want to say thank you so much for this addition. I can think of a one or two ways to use this so far that are exciting me and I can’t wait to see other use cases and examples in action!

**Comment by glibsonoran** [comment] 2024-10-13 22:42
So I made *Additional Parameters* Daisy chain-able:
![Daisy](https://github.com/user-attachments/assets/f3f053e3-90ed-4aa6-af1c-23ce9e326f67)

**Comment by glibsonoran** [comment] 2024-10-15 00:46
The new build is up v.1.21.18.  Let me know if you have any issues.  I had to do some troubleshooting because I was having data carry over issues when daisy-chaining the *Additional Parameters* nodes.  I think this is fixed but keep an eye out.

Hope you have fun with it!  :)

**Comment by glibsonoran** [comment] 2024-10-16 04:47
OK, I'm not all that happy with Additional Parameters.  While it was cool to make a node that could be daisy chained, I thought it was a little clunky.  So here's another design that allow you to save a parameters file if you use consistent setups.  The one drawback is: it's not as robust at checking if your JSON is correctly formatted for the *response_format* parameter. 

Anyway, tell me what you think:

![NewAddParams](https://github.com/user-attachments/assets/19e4e3d4-c095-4b74-b16e-43f3e2ac22ef)

**Comment by EnragedAntelope** [comment] 2024-10-16 18:05
For a reference, I just looked into llm party nodes. Here is their setup for extra parameters:
![image](https://github.com/user-attachments/assets/b60ac84a-ffd3-4543-be93-83d897d3bb7c)

**Comment by glibsonoran** [comment] 2024-10-16 18:40
Here's why I'm not super excited about that idea.  If you look at the list of parameters at OpenAI, Groq etc, a lot of them are deprecated, some of them are new replacements for deprecated items, and some of them, like *response_format* are new altogether, (and I don't see that in Party Node's list).  So this list of parameters is pretty dynamic right now. I don't want to create a node that requires a lot of maintenance on my part (removing deprecated items, adding the new replacement parameters for deprecated items, adding new items.)  
I think this is kind of an advanced user's tool where someone has taken the time to understand what the parameters do.  
I don't really want to make a node like that one... and if you were going to put a text field at the bottom where you could enter parameters that the developer hadn't had time to add/update... well, in my opinion, might as well just do the whole thing that way.

**Comment by glibsonoran** [comment] 2024-10-16 19:15
OK, hope that didn't come off to harsh, I appreciate you sending me ideas.  I just realize a lot of opensource devs burn out because they get bogged down with support and maint.  And then the project just languishes.

**Comment by EnragedAntelope** [comment] 2024-10-16 19:46
Not at all harsh, I totally get it! You explained the rationale well, I’m on board.

**Comment by glibsonoran** [comment] 2024-10-17 04:34
The new Add Parameters node is up on the repo now.

**Comment by EnragedAntelope** [comment] 2024-10-17 13:46
Thank you, just tested and it works great.

For anyone else's reference, here are the settings accepted by the top 3 (to my knowledge) free LLM providers currently, tested and working, along with links to their docs. Note this doesn't mean you should necessarily use all (for instance, the docs don't recommend setting both top_p and temperature together). 

```
Groq:
# https://console.groq.com/docs/api-reference#chat-create

response_format:: {"type": "json_object"}
top_p:: 0.9
temperature:: 1.0
frequency_penalty:: 0.2
presence_penalty:: 0

Sambanova:
# docs at https://cloud.sambanova.ai/apis
# https://api.sambanova.ai/v1/chat/completions

response_format:: {"type": "json_object"}
frequency_penalty:: 0.2
presence_penalty:: 0
temperature:: 1.0
top_p:: 0.9
top_k:: 50

OpenRouter:
# docs at https://openrouter.ai/docs/parameters
# https://openrouter.ai/api/v1/chat/completions

response_format:: {"type": "json_object"}
frequency_penalty:: 0.2
presence_penalty:: 0
temperature:: 1.0
top_p:: 0.9
top_k:: 50
repetition_penalty:: 1.1
```

**Comment by glibsonoran** [comment] 2024-10-29 03:04
@EnragedAntelope I was looking at your stuff again and it seems like parameter configurations are usually model specific rather than service specific.  Do you find these parameters work well with all models on a given service, or is there a particular model these are tailored for?

**Comment by EnragedAntelope** [comment] 2024-10-29 17:50
> @EnragedAntelope I was looking at your stuff again and it seems like parameter configurations are usually model specific rather than service specific. Do you find these parameters work well with all models on a given service, or is there a particular model these are tailored for?

I have noticed that different models support different parameters, especially on openrouter. So it's a pain to try to keep up with. What I've been doing is only using the settings that I find have broad adoption:
frequency_penalty:: 0.2
presence_penalty:: 0
temperature:: 1.0

If I find a use case where I really need finer-grained control then I will use it. So far these are working for me. I wish repeat penalty was more universal but often not needed on the larger/smarter models.

Does that answer your question?

BTW been meaning to ask, is my temperature setting in additional parameters any different from your creative latitude setting in the Adv Prompt Enhancer node? And if they are the same setting, which overrides/"wins"?

**Comment by glibsonoran** [comment] 2024-10-29 18:59
Creative latitude is temperature, I just tried to put it terms that might be better understood by laypersons.  When you put temperature in the additional parameters it overrides the value in creative latitude.

**Comment by glibsonoran** [comment] 2024-12-01 18:58
Closing this issue.

**Closed by glibsonoran** 2024-12-01 18:58 UTC
